version: "3.8"
services:
    web:
        image: ignatovw99/bgapp-web
        deploy:
            replicas: 5
        ports:
            - 8080:80
        volumes:
           - "${PROJECT_ROOT}:/var/www/html"
        networks:
            - app-network
    db:
        image: ignatovw99/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
