version: "3.8"
services:
    php:
        image: php:7.0-fpm
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
        deploy:
            replicas: 3
        networks:
            - app-network
    web:
        image: ignatovw99/bgapp-web
        deploy:
            replicas: 3
        volumes:
            - "${PROJECT_ROOT}:/var/www/html"
        ports:
            - 8080:80
        networks:
            - app-network
    db:
        image: ignatovw99/bgapp-db
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        networks:
            - app-network
networks:
    app-network:
